{"time":"2025-01-25T13:00:34.8383684-06:00","level":"INFO","msg":"stream: starting","core version":"0.19.3","symlink path":"C:\\experiments\\policy-evaluation\\CartPole\\wandb\\run-20250125_130034-r2ogz76j\\logs\\debug-core.log"}
{"time":"2025-01-25T13:00:35.1719442-06:00","level":"INFO","msg":"created new stream","id":"r2ogz76j"}
{"time":"2025-01-25T13:00:35.1719442-06:00","level":"INFO","msg":"stream: started","id":"r2ogz76j"}
{"time":"2025-01-25T13:00:35.1724996-06:00","level":"INFO","msg":"writer: Do: started","stream_id":"r2ogz76j"}
{"time":"2025-01-25T13:00:35.1719442-06:00","level":"INFO","msg":"handler: started","stream_id":"r2ogz76j"}
{"time":"2025-01-25T13:00:35.1724996-06:00","level":"INFO","msg":"sender: started","stream_id":"r2ogz76j"}
{"time":"2025-01-25T13:00:35.3308683-06:00","level":"INFO","msg":"Starting system monitor"}
{"time":"2025-01-25T13:08:56.7153314-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/xuanfeiren-university-of-wisconsin-madison/CartPole-v1/r2ogz76j/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T13:08:56.901175-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T13:18:27.424829-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T13:35:13.1043876-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T13:54:58.8504111-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T14:01:57.212198-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.0.101:51500->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T14:04:38.3400803-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 10.130.180.143:61873->35.186.228.49:443: wsarecv: An established connection was aborted by the software in your host machine."}
{"time":"2025-01-25T14:05:01.4612535-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T14:05:57.5662738-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.0.101:52208->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T14:11:06.2252847-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/xuanfeiren-university-of-wisconsin-madison/CartPole-v1/r2ogz76j/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T14:12:14.753617-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T14:15:43.0244355-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": read tcp 192.168.0.101:63260->35.186.228.49:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T14:17:06.7925971-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/xuanfeiren-university-of-wisconsin-madison/CartPole-v1/r2ogz76j/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T14:20:15.1909607-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T14:27:38.942886-06:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/files/xuanfeiren-university-of-wisconsin-madison/CartPole-v1/r2ogz76j/file_stream\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-01-25T14:29:52.1476914-06:00","level":"INFO","msg":"Stopping system monitor"}
{"time":"2025-01-25T14:29:52.1481971-06:00","level":"INFO","msg":"Stopped system monitor"}
{"time":"2025-01-25T14:29:52.5526379-06:00","level":"INFO","msg":"fileTransfer: Close: file transfer manager closed"}
{"time":"2025-01-25T14:29:52.6229861-06:00","level":"INFO","msg":"handler: operation stats","stats":{}}
{"time":"2025-01-25T14:29:53.642887-06:00","level":"INFO","msg":"stream: closing","id":"r2ogz76j"}
{"time":"2025-01-25T14:29:53.642887-06:00","level":"INFO","msg":"handler: closed","stream_id":"r2ogz76j"}
{"time":"2025-01-25T14:29:53.642887-06:00","level":"INFO","msg":"writer: Close: closed","stream_id":"r2ogz76j"}
{"time":"2025-01-25T14:29:53.642887-06:00","level":"INFO","msg":"sender: closed","stream_id":"r2ogz76j"}
{"time":"2025-01-25T14:29:53.642887-06:00","level":"INFO","msg":"stream: closed","id":"r2ogz76j"}
